<?
$tpl->setVariable('ba_graph_title', WEBPAGE::$gt['RP.GRP.businessActivities']);
$tpl->setVariable('ba_graph', sprintf("<img src='index.pub.graph.php?scr_name=RP.GRP.businessActivities&lang=%s' alt=''>",WEBPAGE::$lang));
$tpl->setVariable('bt_graph_title', WEBPAGE::$gt['RP.GRP.top5business']);
$tpl->setVariable('bt_graph', sprintf("<img src='index.pub.graph.php?scr_name=RP.GRP.top5business&lang=%s' alt=''>",WEBPAGE::$lang));
?>
